#!/bin/bash

USER_ID=$(id -u)
GROUP_ID=$(id -g)

docker run -it --rm \
  --volume=/run/user/${USER_ID}/pulse:/run/user/${GROUP_ID}/pulse \
  --volume="$(pwd)/config":/home/tizonia/.config/tizonia \
  --name tizonia \
  tizonia "$@"
